### ISSUE TITLE
Change links to texlab.netlify.app?

### ISSUE THREAD

**Issue by mpizenberg** [latex-lsp/texlab-web#557]
Hi, when I go to texlab.netlify.com I'm only seeing a blank page. Having a netlify account myself and being aware of the `.com` -> `.app` transition I tested if just switching texlab.netlify.com to texlab.netlify.app would work and it did!

I thought all the `.com` apps should have continue to work but it appears that is not the case here, or maybe a misconfiguration on your part?

**Comment by pfoerster** [comment]
Thanks for the report. It is a bit odd that the redirect doesn't work on your machine. Nevertheless, we changed the links from `.com` to `.app`.
